/**
    [LeetCode 389] Find the Difference

    Given two strings s and t which consist of only lowercase letters.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    
    Find the letter that was added in t.
    Example:
    Input:
    s = "abcd"
    t = "abcde"
    
    Output:
    e
    
    Explanation: 'e' is the letter that was added.

    https://leetcode.com/problems/find-the-difference/description/
 */
class Solution {
    public char findTheDifference(String s, String t) {
        int charCode = t.charAt(s.length());
        for (int i = 0; i < s.length(); i++) {
            charCode -= s.charAt(i);
            charCode += t.charAt(i);
        }
        return (char)charCode;
    }
}